import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import Hero from '@/components/Hero'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Karan Budha Air</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <nav className={styles.navRight}> 
        <div className={styles.navLeft}> 
          <Link href="/">Home</Link>
         <Link href="/projects">Projects</Link>
         <Link href="/about">About</Link> 
         
          </div>

          <div className={styles.navCenter}> 
            <div className={styles.logoCircle}>KB</div> 
          </div> 

          <div className={styles.navRight}> 
            <Link href=" mailto:kunal.neeon@gmail.com"> 
            <Image
                src="/images/svgs/gmail.svg"
                alt="Gmail"
                className={styles.navRight}
                width={28}
                height={28}
                priority
              /> 
            </Link>
          <Link href="https://www.linkedin.com/in/karan-budha-air-a16852152/"> 
            <Image
                src="/images/svgs/linkedIn.svg"
                alt="LinkedIn"
                className={styles.navRight}
                width={28}
                height={28}
                priority
              /> 
            </Link>
            <Link href="https://www.facebook.com/budhaayer"> 
            <Image
                src="/images/svgs/facebook.svg"
                alt="Facebook"
                className={styles.navRight}
                width={28}
                height={28}
                priority
              /> 
            </Link>
            
<Link href="https://github.com/KaranBudhaAir"> 
            <Image
                src="/images/svgs/logo-github.svg"
                alt="Github"
                className={styles.navRight}
                width={28}
                height={28}
                priority
              /> 
            </Link>

            </div>

      </nav>    
<Hero ></Hero>
      






     
    </>
  )
}
